version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "book-store-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hebwxwdvstpc"
s3_prefix = "book-store-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolName=\"DevPool\" CognitoUserPoolClientName=\"DevPoolClient\" CognitoUserPoolApiClientName=\"DevApiPoolClient\""
