service: bookstore

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
     DYNAMODB_TABLE: bookstore_table

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:Get
        - dynamodb:Delete
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/${self:provider.environment.DYNAMODB_TABLE}

resources:
  Resources:
    bookstoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions: 
          - AttributeName: name
            AttributeType: S
          - AttributeName: author
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
          - AttributeName: author
            KeyType: RANGE
        ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

functions:
  put_book:
    handler: backend/put_book.put_item_handler


package:
  include:
    - backend/put_book.py
    - backend/lib/repository.py
  exclude:
    - node_modules/**
    - frontend/**
    - package-lock.json

custom:


#  This one deploys to CloudFront. Requires cache invalidation to propagate updates
#  client:
#    bucketName: mytest-123-bucket-321 # (see Configuration Parameters below)
#    distributionFolder: frontend
#    # [other configuration parameters] (see Configuration Parameters below)


#  Deploys directly to S3 bucket (insecure HTTP)
  client:
    bucketName: test.paolorechia.de  # (see Configuration Parameters below)
    distributionFolder: frontend
